Add Bubblesort method feature
carlos-osorio-developer/bubble-sorting pull request #1
Opened 2021-03-16 20:43 UTC by carlos-osorio-developer

# Add Bubblesort feature

## To add

* algorythm.rb
* .rubocop.yml
* .github/workflows/linters.yml
* .github/workflows/tests.yml

## To update
* README.md

2021-03-16 23:27 UTC, cyonii requested changes
# Status: Changes Required

Hello team, you have shown a great effort in this project, kudos to you.

## Highlights
- Good to have your linters configured and running green 🟢
- Excellent commit messages 👌
- Excellent job keeping your repo clean

## To Improve
You have a great project so far, but there are still vital issues you have to fix in order for this project to be approved, kindly take a look below.
- [ ] Kindly update your PR description so that it describes the changes you intend to merge in. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] Please look at the inline comments and improve your README
- [x] Your `#bubble_sort_by` method failed to sort an array when block is passed, please this, it is vital for this project. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_bubble_sort/sortBy.png) from [Odin](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#assignment-1))
- [x] Please rename your `algorythm.rb` file to `bubble_sort.rb` as this name is important when running tests against your code.

>> ### You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.

2021-03-16 23:27 UTC, cyonii commented on README.md
> +
Your README appear to have few defects, you can use [Grammarly](https://www.grammarly.com) to crosscheck and improve your grammar.

2021-03-16 23:27 UTC, cyonii commented on README.md
> +- git clone gh repo clone https://github.com/carlos-osorio-developer/bubble-sorting/tree/bubblesort
It appears you have made a typo here - `git clone gh repo clone ` -, please fix this typo.

2021-03-17 02:47 UTC, carlos-osorio-developer commented
Hello, thank you for your feedback. Regarding this comment: 

> * [x]  Your `#bubble_sort_by` method failed to sort an array when block is passed, please this, it is vital for this project. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_bubble_sort/sortBy.png) from [Odin](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#assignment-1))

That block is passed into the method at the end of the code, and it is working perfectly when running the command: 

```console
ruby bubble_sort.rb
```

2021-03-17 03:13 UTC, rukundoeric commented on bubble_sort.rb
> +puts "Sorted array: #{bubble_sort([5, 5, 6, 2, 1])}"
debugging codes should be removed before you submit.

2021-03-17 03:16 UTC, rukundoeric requested changes
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve
  - [ ] [MANDATORY] Kindly remove all debugging codes.
  - [ ] [MANDATORY] Your License and issue page  links are broken.
  
_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

2021-03-17 03:39 UTC, rukundoeric requested changes
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve 
  - [x] [MANDATORY] Your License and issue page links are returning `page not found`. kindly fix them before you request another code review.

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

2021-03-17 16:38 UTC, rukundoeric approved these changes
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

2021-03-17 16:50 UTC, merged